### ISSUE TITLE
[1.16.5][Server] CTD when opening Matter Transmitter

### ISSUE THREAD

**Issue by drakray** [McJtyMods/RFToolsUtility#104]
https://pastebin.com/AMxVzB0N
Excerpt for easy search:
```
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.network.PacketBuffer.func_211400_a(PacketBuffer.java:355) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketBuffer.func_180714_a(PacketBuffer.java:351) ~[?:?] {re:classloading}
	at mcjty.lib.typed.Type.lambda$static$4(Type.java:30) ~[mcjtylib:1.16-5.1.0] {re:classloading}
	at mcjty.lib.typed.Type.serialize(Type.java:67) ~[mcjtylib:1.16-5.1.0] {re:classloading}
	at mcjty.lib.varia.Sync$1.toBytes(Sync.java:61) ~[mcjtylib:1.16-5.1.0] {re:classloading}
```

MC : 1.16.5
Forge : 36.2.19
McJtyLib : 1.16-5.1.0
RFToolsBase : 1.16-2.1.0
RFToolsDimensions : 1.16-7.0.16-beta
RFToolsPower : 1.16-3.0.10
RFToolsBuilder : 1.16-3.1.3
RFToolsStorage : 1.16-2.0.14
RFToolsControl : 1.16-4.0.12
RFToolsUtility : 1.16-3.1.4
InControl : 1.16-5.2.2
FxControl : 1.16-2.0.13
+many more, listed in the log

Nothing much to say, was building what is needed to make Dimension, placed Matter Receiver and Transmitter next to an Advanced Dimensional Cell linked to others, set to output. Dialing Device is 2 block above the Cell.
Opened the Receiver to set name, all is good, opened the transmitter, gray screen, then kicked for Server disconnected, server was down with crashLog

**Comment by McJty** [comment]
I can reproduce this. Will fix asap

**Comment by McJty** [comment]
Fixed in latest release of McJtyLib
