### ISSUE TITLE
I can't use Crafter and the Advanced Cherged Porter at the same time.

### ISSUE THREAD

**Issue by sorimicro9** [McJtyMods/RFToolsUtility#114]
Hi, there is a problem in rftoolsutility-1.16-3.1.7, I play with my girlfriend in the local lan server and we like to use Advanced Charged Porter and Matter Receiver for teleportation but for some reason when a Crafter Tier 3 is put in world, my girlfriend is taken out of the world when she tries to teleport.

**Comment by sorimicro9** [comment]
[22:15:57] [Netty Server IO #7/ERROR]: Could not serialize chanceCubes.commands.RewardArgument@7938e766 (class chanceCubes.commands.RewardArgument) - will not be sent to client!
[22:15:57] [Netty Server IO #7/ERROR]: Could not serialize chanceCubes.commands.RewardArgument@294f68ae (class chanceCubes.commands.RewardArgument) - will not be sent to client!
[22:15:57] [Netty Server IO #7/ERROR]: Could not serialize chanceCubes.commands.RewardInfoActionArgument@f184008 (class chanceCubes.commands.RewardInfoActionArgument) - will not be sent to client!
[22:15:57] [Netty Server IO #7/ERROR]: Could not serialize chanceCubes.commands.RewardArgument@5cb901dc (class chanceCubes.commands.RewardArgument) - will not be sent to client!
[22:17:41] [Server thread/INFO]: Server Backup started!
[22:17:41] [Server thread/INFO]: Server Backup started!
[22:17:41] [Render thread/INFO]: [CHAT] Sorimicro launched a manual backup!
[22:17:41] [Thread-142/INFO]: Deleting old backup: 2021-12-29-18-23-42.zip
[22:17:41] [Thread-142/INFO]: Backing up 3533 files...
[22:17:41] [Thread-142/INFO]: Compressing 3533 files...
[22:17:41] [Server thread/INFO]: [0 | 0%]: technomagicrage\advancements\032e850b-d798-3a62-ac8a-6b2e406df360.json
[22:18:59] [Server thread/INFO]: [3532 | 99%]: technomagicrage\tombstone\saved_players\d76fcd1f-32ef-45d9-8d57-dab69cee2e67\20211229-221044.save
[22:18:59] [Thread-142/INFO]: Done compressing in 01:17 seconds (2.4GB)!
[22:18:59] [Thread-142/INFO]: Created C:\Users\Constantine\AppData\Roaming\gdlauncher_next\instances\1sorimicro1\backups\2021-12-29-22-17-41.zip from C:\Users\Constantine\AppData\Roaming\gdlauncher_next\instances\1sorimicro1\saves\technomagicrage
[22:18:59] [Thread-142/INFO]: Server backup done in 01:17! (2.4GB | 32.9GB)
[22:18:59] [Render thread/INFO]: [CHAT] Server backup done in 01:17! (2.4GB | 32.9GB)
[22:19:06] [Render thread/WARN]: Image not found: illagers_plus:textures/entity_icon/necromancer.png
[22:19:06] [Render thread/WARN]: Image not found: illagers_plus:textures/entity_icon/enchanter.png
[22:19:06] [Render thread/WARN]: Image not found: illagers_plus:textures/entity_icon/furantur.png
[22:19:29] [Render thread/ERROR]: Error finding field of field_191217_a from field_191217_a for HeadInfo of model ModelEnchanter in RenderEntityEnchanter
[22:19:29] [Render thread/ERROR]: Error finding field of field_191217_a from field_191217_a for HeadInfo of model ModelNecromancer in RenderEntityNecromancer
[22:20:53] [Render thread/INFO]: [mod.beethoven92.betterendforge.common.block.StalactiteBlock:func_196258_a:86]: Check down!
[22:20:55] [Render thread/INFO]: [mod.beethoven92.betterendforge.common.block.StalactiteBlock:func_196258_a:86]: Check down!
[22:23:25] [Server thread/INFO]: nicoletamicro has unlocked Dark Egg trinket
[22:23:25] [Render thread/INFO]: [CHAT] nicoletamicro has unlocked Dark Egg trinket
[22:25:48] [Server thread/WARN]: Fetching packet for removed entity ItemEntity['Loot Bag'/446401, l='ServerLevel[technomagicrage]', x=99.38, y=47.18, z=214.56]
[22:25:48] [Netty Server IO #7/ERROR]: Error encoding packet
io.netty.util.IllegalReferenceCountException: refCnt: 0
at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1417) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1356) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
at io.netty.buffer.UnpooledHeapByteBuf.copy(UnpooledHeapByteBuf.java:538) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
at io.netty.buffer.AbstractByteBuf.copy(AbstractByteBuf.java:1170) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
at net.minecraft.network.PacketBuffer.copy(PacketBuffer.java:1009) ~[?:?]
at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148840_b(SCustomPayloadPlayPacket.java:55) ~[?:?]
at net.minecraft.network.NettyPacketEncoder.encode(NettyPacketEncoder.java:38) ~[?:?]
at net.minecraft.network.NettyPacketEncoder.encode(NettyPacketEncoder.java:12) ~[?:?]
at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
at net.minecraft.network.NetworkManager.lambda$sendPacket$5(NetworkManager.java:196) ~[?:?]
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-all-4.1.25.Final.jar:4.1.25.Final]
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [netty-all-4.1.25.Final.jar:4.1.25.Final]
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465) [netty-all-4.1.25.Final.jar:4.1.25.Final]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [netty-all-4.1.25.Final.jar:4.1.25.Final]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
[22:25:48] [Netty Server IO #7/ERROR]: Error encoding packet
io.netty.util.IllegalReferenceCountException: refCnt: 0
at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1417) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1356) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
at io.netty.buffer.UnpooledHeapByteBuf.copy(UnpooledHeapByteBuf.java:538) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
at io.netty.buffer.AbstractByteBuf.copy(AbstractByteBuf.java:1170) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
at net.minecraft.network.PacketBuffer.copy(PacketBuffer.java:1009) ~[?:?]
at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148840_b(SCustomPayloadPlayPacket.java:55) ~[?:?]
at net.minecraft.network.NettyPacketEncoder.encode(NettyPacketEncoder.java:38) ~[?:?]
at net.minecraft.network.NettyPacketEncoder.encode(NettyPacketEncoder.java:12) ~[?:?]
at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
at net.minecraft.network.NetworkManager.lambda$sendPacket$5(NetworkManager.java:196) ~[?:?]
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-all-4.1.25.Final.jar:4.1.25.Final]
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [netty-all-4.1.25.Final.jar:4.1.25.Final]
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465) [netty-all-4.1.25.Final.jar:4.1.25.Final]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [netty-all-4.1.25.Final.jar:4.1.25.Final]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
[22:25:49] [Server thread/INFO]: nicoletamicro lost connection: Internal Exception: io.netty.handler.codec.EncoderException: io.netty.util.IllegalReferenceCountException: refCnt: 0
[22:25:49] [Server thread/INFO]: nicoletamicro left the game
[22:25:49] [Render thread/INFO]: [CHAT] nicoletamicro left the game
[22:31:44] [Server thread/INFO]: All players have been successfully backed up
[22:32:41] [Server thread/INFO]: Server Backup started!
[22:32:41] [Server thread/INFO]: Server Backup started!
[22:32:41] [Thread-152/INFO]: Deleting old backup: 2021-12-29-18-38-42.zip
[22:32:41] [Thread-152/INFO]: Backing up 3539 files...
[22:32:41] [Thread-152/INFO]: Compressing 3539 files...
[22:32:41] [Server thread/INFO]: [0 | 0%]: technomagicrage\advancements\032e850b-d798-3a62-ac8a-6b2e406df360.json
[22:33:58] [Server thread/INFO]: [3538 | 99%]: technomagicrage\tombstone\saved_players\d76fcd1f-32ef-45d9-8d57-dab69cee2e67\20211229-221044.save
[22:33:58] [Thread-152/INFO]: Done compressing in 01:16 seconds (2.4GB)!
[22:33:58] [Thread-152/INFO]: Created C:\Users\Constantine\AppData\Roaming\gdlauncher_next\instances\1sorimicro1\backups\2021-12-29-22-32-41.zip from C:\Users\Constantine\AppData\Roaming\gdlauncher_next\instances\1sorimicro1\saves\technomagicrage
[22:33:58] [Thread-152/INFO]: Server backup done in 01:16! (2.4GB | 33.1GB)
[22:33:58] [Render thread/INFO]: [CHAT] Server backup done in 01:16! (2.4GB | 33.1GB)

**Comment by sorimicro9** [comment]
sorry i think i close by mistake

**Comment by sorimicro9** [comment]
I forgot to mention that we both need to restart the pack so that it can go back into the world.

**Comment by McJty** [comment]
This looks like a problem with chance cubes to be honest
