### ISSUE TITLE
[1.18-4.0.3] Client crash when attempting to view the connected users list

### ISSUE THREAD

**Issue by StarkRG** [McJtyMods/RFToolsUtility#119]
While connected to a server running ATM7 (version 0.2.21), pressing <tab> to bring up the list of connected users the client crashes to desktop providing the following error:
`FATAL ERROR in native method: Thread[Render thread,5,main]: No context is current or a function that is not available in the current context was called. The JVM will abort execution.
	at org.lwjgl.opengl.GL11.glColor4f(org.lwjgl.opengl/Native Method)
	at mcjty.rftoolsutility.client.RenderGameOverlayEventHandler.lambda$renderBuffs$0(rftoolsutility@1.18-4.0.3/RenderGameOverlayEventHandler.java:70)
	at mcjty.rftoolsutility.client.RenderGameOverlayEventHandler$$Lambda$31306/0x00000008044b7188.accept(rftoolsutility@1.18-4.0.3/Unknown Source)
	at net.minecraftforge.common.util.LazyOptional.ifPresent(forge@39.0.10/LazyOptional.java:164)
	at mcjty.rftoolsutility.client.RenderGameOverlayEventHandler.renderBuffs(rftoolsutility@1.18-4.0.3/RenderGameOverlayEventHandler.java:43)
	at mcjty.rftoolsutility.client.RenderGameOverlayEventHandler.onRender(rftoolsutility@1.18-4.0.3/RenderGameOverlayEventHandler.java:30)
	at mcjty.rftoolsutility.setup.ClientSetup.renderGameOverlayEvent(rftoolsutility@1.18-4.0.3/ClientSetup.java:33)
	at mcjty.rftoolsutility.RFToolsUtility$$Lambda$14334/0x0000000802a161a8.accept(rftoolsutility@1.18-4.0.3/Unknown Source)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(eventbus@5.0.3/EventBus.java:247)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(eventbus@5.0.3/EventBus.java:239)
	at net.minecraftforge.eventbus.EventBus$$Lambda$3919/0x000000080182afa8.invoke(eventbus@5.0.3/Unknown Source)
	at net.minecraftforge.eventbus.EventBus$$Lambda$4089/0x000000080188d7f8.invoke(eventbus@5.0.3/Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(eventbus@5.0.3/EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(eventbus@5.0.3/EventBus.java:283)
	at net.minecraftforge.client.gui.ForgeIngameGui.pre(forge@39.0.10/ForgeIngameGui.java:876)
	at net.minecraftforge.client.gui.ForgeIngameGui.renderPlayerList(forge@39.0.10/ForgeIngameGui.java:815)
	at net.minecraftforge.client.gui.ForgeIngameGui.lambda$static$25(forge@39.0.10/ForgeIngameGui.java:332)
	at net.minecraftforge.client.gui.ForgeIngameGui$$Lambda$20555/0x0000000803516ca0.render(forge@39.0.10/Unknown Source)
	at net.minecraftforge.client.gui.ForgeIngameGui.lambda$render$26(forge@39.0.10/ForgeIngameGui.java:363)
	at net.minecraftforge.client.gui.ForgeIngameGui$$Lambda$30671/0x0000000804393b18.accept(forge@39.0.10/Unknown Source)
	at java.util.ArrayList.forEach(java.base@17.0.1/ArrayList.java:1511)
	at java.util.Collections$UnmodifiableCollection.forEach(java.base@17.0.1/Collections.java:1092)
	at net.minecraftforge.client.gui.ForgeIngameGui.m_93030_(forge@39.0.10/ForgeIngameGui.java:357)
	at net.minecraft.client.renderer.GameRenderer.m_109093_(minecraft@1.18.1/GameRenderer.java:866)
	at net.minecraft.client.Minecraft.m_91383_(minecraft@1.18.1/Minecraft.java:1040)
	at net.minecraft.client.Minecraft.m_91374_(minecraft@1.18.1/Minecraft.java:660)
	at net.minecraft.client.main.Main.main(minecraft@1.18.1/Main.java:205)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@17.0.1/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@17.0.1/NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@17.0.1/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@17.0.1/Method.java:568)
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(fmlloader@1.18.1-39.0.10/CommonClientLaunchHandler.java:45)
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler$$Lambda$809/0x00000008010e54e0.call(fmlloader@1.18.1-39.0.10/Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(cpw.mods.modlauncher@9.0.7/LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(cpw.mods.modlauncher@9.0.7/LaunchServiceHandler.java:53)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(cpw.mods.modlauncher@9.0.7/LaunchServiceHandler.java:71)
	at cpw.mods.modlauncher.Launcher.run(cpw.mods.modlauncher@9.0.7/Launcher.java:106)
	at cpw.mods.modlauncher.Launcher.main(cpw.mods.modlauncher@9.0.7/Launcher.java:77)
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(cpw.mods.modlauncher@9.0.7/BootstrapLaunchConsumer.java:26)
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(cpw.mods.modlauncher@9.0.7/BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(cpw.mods.bootstraplauncher@0.1.17/BootstrapLauncher.java:90)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@17.0.1/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@17.0.1/NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@17.0.1/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@17.0.1/Method.java:568)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@17.0.1/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@17.0.1/NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@17.0.1/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@17.0.1/Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)`

**Comment by McJty** [comment]
Update. This has been fixed
