### ISSUE TITLE
Poison in Environmental Controller causes crash

### ISSUE THREAD

**Issue by SWCreeperKing** [McJtyMods/RFToolsUtility#129]
putting a poison module in an Environmental Controller while set to Mobs causes an error and crashes

version: 1.18 - 4.0.7

[crash-2022-03-17_15.36.26-server.txt](https://github.com/McJtyMods/RFToolsUtility/files/8293245/crash-2022-03-17_15.36.26-server.txt)
Edit: attached crash log
```
net.minecraft.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:872) ~[server-1.18.1-20211210.034407-srg.jar%23234!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:328) ~[server-1.18.1-20211210.034407-srg.jar%23234!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[server-1.18.1-20211210.034407-srg.jar%23234!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[server-1.18.1-20211210.034407-srg.jar%23234!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%23234!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.entity.EntityTypeTest.m_142225_()" because "p_188349_" is null
	at net.minecraft.world.level.entity.EntitySection.m_188348_(EntitySection.java:41) ~[server-1.18.1-20211210.034407-srg.jar%23234!/:?]
	at net.minecraft.world.level.entity.EntitySectionStorage.m_188357_(EntitySectionStorage.java:122) ~[server-1.18.1-20211210.034407-srg.jar%23234!/:?]
	at net.minecraft.world.level.entity.EntitySectionStorage.m_188362_(EntitySectionStorage.java:63) ~[server-1.18.1-20211210.034407-srg.jar%23234!/:?]
	at net.minecraft.world.level.entity.EntitySectionStorage.m_156863_(EntitySectionStorage.java:122) ~[server-1.18.1-20211210.034407-srg.jar%23234!/:?]
	at net.minecraft.world.level.entity.LevelEntityGetterAdapter.m_142137_(LevelEntityGetterAdapter.java:47) ~[server-1.18.1-20211210.034407-srg.jar%23234!/:?]
	at net.minecraft.world.level.Level.m_142425_(Level.java:617) ~[server-1.18.1-20211210.034407-srg.jar%23234!/:?]
	at mcjty.rftoolsutility.modules.environmental.modules.PotionEffectModule.processEntities(PotionEffectModule.java:94) ~[rftoolsutility-1.18-4.0.7.jar%23187!/:1.18-4.0.7]
	at mcjty.rftoolsutility.modules.environmental.modules.PotionEffectModule.tick(PotionEffectModule.java:65) ~[rftoolsutility-1.18-4.0.7.jar%23187!/:1.18-4.0.7]
	at mcjty.rftoolsutility.modules.environmental.blocks.EnvironmentalControllerTileEntity.tickServer(EnvironmentalControllerTileEntity.java:345) ~[rftoolsutility-1.18-4.0.7.jar%23187!/:1.18-4.0.7]
	at mcjty.lib.tileentity.TickingTileEntity.tick(TickingTileEntity.java:18) ~[mcjtylib-1.18-6.0.8.jar%23148!/:1.18-6.0.8]
	at mcjty.lib.blocks.BaseBlock.runTick(BaseBlock.java:345) ~[mcjtylib-1.18-6.0.8.jar%23148!/:1.18-6.0.8]
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:673) ~[server-1.18.1-20211210.034407-srg.jar%23234!/:?]
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:768) ~[server-1.18.1-20211210.034407-srg.jar%23234!/:?]
	at net.minecraft.world.level.Level.m_46463_(Level.java:476) ~[server-1.18.1-20211210.034407-srg.jar%23234!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:324) ~[server-1.18.1-20211210.034407-srg.jar%23234!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868) ~[server-1.18.1-20211210.034407-srg.jar%23234!/:?]
	... 5 more

**Comment by McJty** [comment]
This works fine for me. But I noticed you have an old version of forge. You should update
