### ISSUE TITLE
RFToolsBase failed to load correctly

### ISSUE THREAD

**Issue by isBucky** [McJtyMods/RFToolsUtility#172]
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 2023-03-26 21:46:50
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.19.2-43.2.0-universal.jar%23219!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:167) ~[forge-1.19.2-43.2.0-universal.jar%23219!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:585) ~[client-1.19.2-20220805.130853-srg.jar%23214!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:438) ~[client-1.19.2-20220805.130853-srg.jar%23214!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$3(Minecraft.java:579) ~[client-1.19.2-20220805.130853-srg.jar%23214!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:135) ~[client-1.19.2-20220805.130853-srg.jar%23214!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:885) ~[client-1.19.2-20220805.130853-srg.jar%23214!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23214!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23214!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23214!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23214!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.0.jar%2390!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2377!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2377!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2377!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2377!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2377!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2377!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2377!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at mcjty.rftoolsbase.setup.ModSetup.<init>(ModSetup.java:22) ~[RFTools-Base-Mod-Forge-1.19.2.jar%23203!/:1.19.1-4.0.2] {re:classloading}
-- MOD rftoolsbase --
Details:
	Mod File: /home/bucky/.minecraft/mods/RFTools-Base-Mod-Forge-1.19.2.jar
	Failure message: RFToolsBase (rftoolsbase) has failed to load correctly
		java.lang.NoSuchMethodError: 'void mcjty.rftoolsbase.setup.ModSetup.createTab(java.lang.String, java.util.function.Supplier)'
	Mod Version: 1.19.1-4.0.2
	Mod Issue URL: http://github.com/McJtyMods/RFToolsBase/issues
	Exception message: java.lang.NoSuchMethodError: 'void mcjty.rftoolsbase.setup.ModSetup.createTab(java.lang.String, java.util.function.Supplier)'
Stacktrace:
	at mcjty.rftoolsbase.setup.ModSetup.<init>(ModSetup.java:22) ~[RFTools-Base-Mod-Forge-1.19.2.jar%23203!/:1.19.1-4.0.2] {re:classloading}
	at mcjty.rftoolsbase.RFToolsBase.<clinit>(RFToolsBase.java:34) ~[RFTools-Base-Mod-Forge-1.19.2.jar%23203!/:1.19.1-4.0.2] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.0.jar%23216!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.0.jar%23215!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- MOD rftoolsutility --
Details:
	Mod File: /home/bucky/.minecraft/mods/RFTools-Utility-Mod-Forge-1.19.2.jar
	Failure message: RFToolsUtility (rftoolsutility) has failed to load correctly
		java.lang.NoSuchMethodError: 'void mcjty.rftoolsutility.setup.ModSetup.createTab(java.lang.String, java.util.function.Supplier)'
	Mod Version: 1.19-5.0.3
	Mod Issue URL: http://github.com/McJtyMods/RFToolsUtility/issues
	Exception message: java.lang.NoSuchMethodError: 'void mcjty.rftoolsutility.setup.ModSetup.createTab(java.lang.String, java.util.function.Supplier)'
Stacktrace:
	at mcjty.rftoolsutility.setup.ModSetup.<init>(ModSetup.java:21) ~[RFTools-Utility-Mod-Forge-1.19.2.jar%23205!/:1.19-5.0.3] {re:classloading}
	at mcjty.rftoolsutility.RFToolsUtility.<clinit>(RFToolsUtility.java:36) ~[RFTools-Utility-Mod-Forge-1.19.2.jar%23205!/:1.19-5.0.3] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.0.jar%23216!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.0.jar%23215!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- MOD rftoolsbuilder --
Details:
	Mod File: /home/bucky/.minecraft/mods/RFTools-Builder-Mod-Forge-1.19.2.jar
	Failure message: RFToolsBuilder (rftoolsbuilder) has failed to load correctly
		java.lang.NoSuchMethodError: 'void mcjty.rftoolsbuilder.setup.ModSetup.createTab(java.lang.String, java.util.function.Supplier)'
	Mod Version: 1.19.1-5.0.4
	Mod Issue URL: http://github.com/McJtyMods/RFToolsBuilder/issues
	Exception message: java.lang.NoSuchMethodError: 'void mcjty.rftoolsbuilder.setup.ModSetup.createTab(java.lang.String, java.util.function.Supplier)'
Stacktrace:
	at mcjty.rftoolsbuilder.setup.ModSetup.<init>(ModSetup.java:12) ~[RFTools-Builder-Mod-Forge-1.19.2.jar%23204!/:1.19.1-5.0.4] {re:classloading}
	at mcjty.rftoolsbuilder.RFToolsBuilder.<clinit>(RFToolsBuilder.java:24) ~[RFTools-Builder-Mod-Forge-1.19.2.jar%23204!/:1.19.1-5.0.4] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.0.jar%23216!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.0.jar%23215!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Linux (amd64) version 6.2.7-2-MANJARO
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 292433856 bytes (278 MiB) / 872415232 bytes (832 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5500U with Radeon Graphics
	Identifier: AuthenticAMD Family 23 Model 104 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Lucienne
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MB): 258.00
	Graphics card #0 deviceId: 0x164c
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 8916.45
	Virtual memory used (MB): 6513.43
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.2-43.2.0.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.2-43.2.0.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.2-43.2.0.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.2-43.2.0.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.2-43.2.0.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		SmartBrainLib-Mod-Forge-1.19.2.jar                |SmartBrainLib                 |smartbrainlib                 |1.8                 |COMMON_SET|Manifest: NOSIGNATURE
		YUNGs-Better-Ocean-Monuments-Mod-Forge-1.19.2.jar |YUNG's Better Ocean Monuments |betteroceanmonuments          |1.19.2-Forge-2.1.0  |COMMON_SET|Manifest: NOSIGNATURE
		Curios-API-Forge-1.19.2.jar                       |Curios API                    |curios                        |1.19.2-5.1.1.0      |COMMON_SET|Manifest: NOSIGNATURE
		Mekanism-Mod-Core-Forge-1.19.2.jar                |Mekanism                      |mekanism                      |10.3.4              |COMMON_SET|Manifest: NOSIGNATURE
		Mekanism-Mod-Additions-Forge-1.19.2.jar           |Mekanism: Additions           |mekanismadditions             |10.3.4              |COMMON_SET|Manifest: NOSIGNATURE
		Waystones-Mod-Forge-1.19.2.jar                    |Waystones                     |waystones                     |11.2.0              |COMMON_SET|Manifest: NOSIGNATURE
		JourneyMap-Mod-Forge-1.19.2.jar                   |Journeymap                    |journeymap                    |5.9.4               |COMMON_SET|Manifest: NOSIGNATURE
		Travelers-Backpack-Mod-Forge-1.19.2.jar           |Traveler's Backpack           |travelersbackpack             |8.2.15              |COMMON_SET|Manifest: NOSIGNATURE
		Flux-Networks-Mod-Forge-1.19.2.jar                |Flux Networks                 |fluxnetworks                  |7.1.1.10            |COMMON_SET|Manifest: NOSIGNATURE
		YUNGs-Extras-Mod-Forge-1.19.2.jar                 |YUNG's Extras                 |yungsextras                   |1.19.2-Forge-3.1.0  |COMMON_SET|Manifest: NOSIGNATURE
		Time-in-a-Bottle-Mod-Forge-1.19.2.jar             |Time In A Bottle              |tiab                          |3.0.1-mc1.19        |COMMON_SET|Manifest: NOSIGNATURE
		YUNGs-API-Forge-1.19.2.jar                        |YUNG's API                    |yungsapi                      |1.19.2-Forge-3.8.2  |COMMON_SET|Manifest: NOSIGNATURE
		OpenBlocks-Elevator-Mod-Forge-1.19.2.jar          |Elevator Mod                  |elevatorid                    |1.19.2-1.8.9        |COMMON_SET|Manifest: NOSIGNATURE
		Botany-Pots-Mod-Forge-1.19.2.jar                  |BotanyPots                    |botanypots                    |9.0.27              |COMMON_SET|Manifest: NOSIGNATURE
		Bookshelf-API-Library-Forge-1.19.2.jar            |Bookshelf                     |bookshelf                     |16.1.5              |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		Modonomicon-Mod-Forge-1.19.2.jar                  |Modonomicon                   |modonomicon                   |1.19.2-1.27.0       |COMMON_SET|Manifest: NOSIGNATURE
		Mekanism-Mod-Tools-Forge-1.19.2.jar               |Mekanism: Tools               |mekanismtools                 |10.3.4              |COMMON_SET|Manifest: NOSIGNATURE
		McJtyLib-Forge-1.19.2.jar                         |McJtyLib                      |mcjtylib                      |1.19-7.1.5          |COMMON_SET|Manifest: NOSIGNATURE
		RFTools-Base-Mod-Forge-1.19.2.jar                 |RFToolsBase                   |rftoolsbase                   |1.19.1-4.0.2        |ERROR     |Manifest: NOSIGNATURE
		RFTools-Utility-Mod-Forge-1.19.2.jar              |RFToolsUtility                |rftoolsutility                |1.19-5.0.3          |ERROR     |Manifest: NOSIGNATURE
		RFTools-Builder-Mod-Forge-1.19.2.jar              |RFToolsBuilder                |rftoolsbuilder                |1.19.1-5.0.4        |ERROR     |Manifest: NOSIGNATURE
		Architectury-API-Mod-Forge-1.19.2.jar             |Architectury                  |architectury                  |6.3.49              |COMMON_SET|Manifest: NOSIGNATURE
		Item-Filters-Mod-Forge-1.19.2.jar                 |Item Filters                  |itemfilters                   |1902.2.9-build.41   |COMMON_SET|Manifest: NOSIGNATURE
		Occultism-Mod-Forge-1.19.2.jar                    |Occultism                     |occultism                     |1.19.2-1.72.0       |COMMON_SET|Manifest: NOSIGNATURE
		Mekanism-Mod-Generators-Forge-1.19.2.jar          |Mekanism: Generators          |mekanismgenerators            |10.3.4              |COMMON_SET|Manifest: NOSIGNATURE
		Balm-Mod-Forge-1.19.2.jar                         |Balm                          |balm                          |4.5.4               |COMMON_SET|Manifest: NOSIGNATURE
		EdivadLib-Mod-Forge-1.19.2.jar                    |EdivadLib                     |edivadlib                     |1.2.0               |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.19.2-43.2.0-universal.jar                 |Forge                         |forge                         |43.2.0              |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		Mob-Grinding-Utils-Mod-Forge-1.19.2.jar           |Mob Grinding Utils            |mob_grinding_utils            |1.19-0.4.45         |COMMON_SET|Manifest: NOSIGNATURE
		Refined-Storage-Mod-Forge-1.19.2.jar              |Refined Storage               |refinedstorage                |1.11.0              |COMMON_SET|Manifest: NOSIGNATURE
		ExtraStorage-Mod-Forge-1.19.2.jar                 |Extra Storage                 |extrastorage                  |3.0.1               |COMMON_SET|Manifest: NOSIGNATURE
		GeckoLib-Mod-Forge-1.19.2.jar                     |GeckoLib                      |geckolib3                     |3.1.40              |COMMON_SET|Manifest: NOSIGNATURE
		Iron-Chests-Mod-Forge-1.19.2.jar                  |Iron Chests                   |ironchest                     |1.19.2-14.2.7       |COMMON_SET|Manifest: NOSIGNATURE
		All-the-Ores-Mod-Forge-1.19.2.jar                 |AllTheOres                    |alltheores                    |2.0.0g-1.19.2-43.1.1|COMMON_SET|Manifest: NOSIGNATURE
		Useless-Swords-Mod-Forge-1.19.2.jar               |Useless Sword                 |useless_sword                 |1.4.1               |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: 68523b2a-6e63-4d34-8cda-fcf1877cfe58
	FML: 43.2
	Forge: net.minecraftforge:43.2.0

**Comment by isBucky** [comment]
wrong repository
