### ISSUE TITLE
Crafter doesn't seem to work on dedicated server

### ISSUE THREAD

**Issue by RakSrinaNa** [McJtyMods/RFToolsUtility#4]
Tried to use the crafter but nothing happens on a dedicated server. Doing the same in single player does work though.

Things I've noticed:
- The power is correct with waila but when entering the machine it displays `-15536/50000`. Clicking on `R`, `F`, `Redstone mode` or `Speed mode` updates it and displays the same value as waila.
- The crafting doesn't seem to work mainly because the craft isn't being saved. Do a configuration, leave the crafter, open it again and it's all blank.

Maybe things happens only on the GUI client side and don't get sync with the server?

I saw this in the server log but can't tell at all if it is related to this mod: 
```
[30Oct2019 11:27:33.727] [Server thread/ERROR] [net.minecraftforge.fml.network.simple.IndexedMessageCodec/SIMPLENET]: Received invalid discriminator byte 23
```

### Versions

- Forge: 1.14.4-28.1.74
- RFTools Utility: 1.14-1.2.6
- RFTools Base: 1.14-0.0.6
- McJtyLib: 1.14-3.5.9

**Comment by McJty** [comment]
Can you give me a bit more log to work with? Thanks

**Comment by RakSrinaNa** [comment]
I can give you the logs but nothing seems to really crash in there.
I used the same pack of mods when trying server and singleplayer.

[Logs](https://gist.github.com/RakSrinaNa/02102b3b1bdfeaebb62f02b43c842993)

In the server part, around line I just connected opened the crafter gui clicked a bit around and disconnected.

**Comment by McJty** [comment]
I would like to see the log around that line you noticed above with the 'Received invalid discriminator'. The log you pasted above doesn't seem to contain that line

**Comment by RakSrinaNa** [comment]
Server log lines:
- 17007
- 17034
- 17455

I'm trying to setup a little env with less mods to get cleaner logs

**Comment by McJty** [comment]
Ah didn't notice your gist contained more logs

**Comment by McJty** [comment]
But I still can't find it. Also searching in that server-debug.log doesn't yield anything

**Comment by RakSrinaNa** [comment]
It's fine, they're too massive and should have did it in a cleaner env before reporting it.

I edited the gist with a better env. This time though it behaved a bit differently. The energy went up and the went to -20k or something a bit latter. The byte thing is still here though (line 962 of server log).

**Comment by McJty** [comment]
Thanks. I will investigate

**Comment by RakSrinaNa** [comment]
I tried it again today and the main issue seem to be gone. I don't now if it's because of the mcjtylib lib update or because of the upgrade of forge to `28.1.79`. The crafts are now remembered, working and the message about the invalid discriminator is gone.

Though the display of the energy is still wrong and goes into the negative.

**Comment by McJty** [comment]
I made some changes but wasn't sure they would fix it as I could not reproduce the problem. Thanks for confirming. I'll check the energy problem

**Comment by RakSrinaNa** [comment]
Weirdly it seems to be back. I broke a crafter to move it, and then when trying to use it again the same problem appeared. Weirdly only one of the 2 I have broke, the other still crafted fine.

A weird thing I noticed, but that happened only on the server with all the mods, pressing `Apply` in the crafter gives an exception. But an exception that seems related to the teleporter.

```
[07Nov2019 11:10:55.689] [Server thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
java.lang.IndexOutOfBoundsException: readerIndex(13) + length(65793) exceeds writerIndex(62): PooledUnsafeDirectByteBuf(ridx: 13, widx: 62, cap: 62)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1405) ~[server-1.14.4-extra-stable.jar:?]
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1392) ~[server-1.14.4-extra-stable.jar:?]
	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:872) ~[server-1.14.4-extra-stable.jar:?]
	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:880) ~[server-1.14.4-extra-stable.jar:?]
	at net.minecraft.network.PacketBuffer.readBytes(PacketBuffer.java:828) ~[?:?]
	at mcjty.lib.network.NetworkTools.readString(NetworkTools.java:57) ~[?:1.14-3.5.10-alpha]
	at mcjty.rftoolsutility.modules.teleporter.network.PacketTransmittersReady.<init>(PacketTransmittersReady.java:29) ~[?:1.14-1.2.7-alpha]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$0(IndexedMessageCodec.java:106) ~[?:?]
	at java.util.Optional.map(Unknown Source) ~[?:1.8.0_201]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:106) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:147) ~[?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:79) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:84) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$0(NetworkHooks.java:74) ~[?:?]
	at java.util.Optional.map(Unknown Source) ~[?:1.8.0_201]
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:74) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:1275) ~[?:?]
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:42) ~[?:?]
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:12) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:699) [?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:693) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:679) [?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:626) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
```

As I can't really reproduce it on the cleaner environment it may be due to other mods though.
Or my world is broken 😆

**Comment by RakSrinaNa** [comment]
As you can't reproduce it I give you the [server I tested it with](https://www.dropbox.com/s/s8r0t78hr1giec3/server-McJtyMods-RFToolsUtility-4.zip?dl=1) if it can help.
Of course for the client part, just use the same. Though I removed the `minecraft_server.1.14.4.jar` file as I don't know if we're allowed to distribute it.

**Comment by McJty** [comment]
Thanks. I'll try to find time to check it out although I already did some changes which might help.

**Comment by McJty** [comment]
I don't see how it is even possible to get such a stacktrace. Seems as if networking is somehow totally garbled

**Comment by McJty** [comment]
Also could you try to update forge? I see there are some better diagnostics in forge >= 80 so it might be nice to see if we get better errors then

**Comment by RakSrinaNa** [comment]
Yeah it's super weird.

I'll try again with the latest forge and see.

**Comment by RakSrinaNa** [comment]
For the stacktrace I don't know if it is really relevant as I couldn't reproduce it with the cleaner env. Maybe something else causing it.

Though updating forge doesn't tell much much more. Though it confirms the mod for the discriminator:
`[07Nov2019 15:40:18.416] [Server thread/ERROR] [net.minecraftforge.fml.network.simple.IndexedMessageCodec/SIMPLENET]: Received invalid discriminator byte 14 on channel rftoolsutility:rftoolsutility`

**Comment by RakSrinaNa** [comment]
I tried again after trying to reset various things. On a fully clean env I can't reproduce it either.

Though it seems to be linked to the world save I have (as I can reproduce it there). Maybe it is somehow corrupted.

**Comment by RakSrinaNa** [comment]
The problems seems to be fixed. The energy problem as stated in the lib changelog, as well as the discriminator byte. (on the clean env)

Though pressing apply on my real server leads to an exception, and again a weird one:
```
java.lang.NoSuchMethodError: net.minecraft.network.PacketBuffer.func_218666_n()Ljava/lang/String;
	at mcjty.rftoolsutility.modules.teleporter.network.PacketTransmittersReady.<init>(PacketTransmittersReady.java:28) ~[?:1.14-1.2.8-alpha] {re:classloading}
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$0(IndexedMessageCodec.java:116) ~[?:?] {re:classloading}
	at java.util.Optional.map(Unknown Source) ~[?:1.8.0_201] {}
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:116) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:157) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:79) ~[?:?] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:84) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$0(NetworkHooks.java:74) ~[?:?] {re:classloading}
	at java.util.Optional.map(Unknown Source) ~[?:1.8.0_201] {}
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:74) ~[?:?] {re:classloading}
	at net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:1275) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:42) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:12) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:699) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:693) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:679) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:626) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201] {}
```

As I can't reproduce it in a clean env I'll consider that it comes somewhere in my modpack/corrupted map.

**Comment by RakSrinaNa** [comment]
Bad new I guess, I managed to make the bug happen again 😆 As you can't reproduce things, I took a video of it: https://youtu.be/UmUmRHKcyag 

[From 00:00 to 02:37 in the video] Actually managed to make it happen again (same exception as last message) on a newly created map. Happening when pressing the redstone mode button (~01:28 in the video).

[From 02:37 to the end in the video] Weird thing again (as everything is weird here), I tried to do again a new map and test it another time. But this time the GUI doesn't even open and an error happens on the client side.
```
[11Nov2019 09:15:24.912] [Client thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Client
java.lang.IndexOutOfBoundsException: readerIndex(1) + length(8) exceeds writerIndex(2): PooledUnsafeDirectByteBuf(ridx: 1, widx: 2, cap: 2)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1405) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.buffer.AbstractByteBuf.readLong(AbstractByteBuf.java:812) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at net.minecraft.network.PacketBuffer.readLong(PacketBuffer.java:784) ~[?:?]
	at net.minecraft.network.PacketBuffer.func_179259_c(PacketBuffer.java:139) ~[?:?]
	at mcjty.rftoolsutility.modules.screen.network.PacketReturnScreenData.<init>(PacketReturnScreenData.java:45) ~[?:1.14-1.2.8-alpha]
	at mcjty.rftoolsutility.network.RFToolsUtilityMessages$$Lambda$2727/1609673087.apply(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$0(IndexedMessageCodec.java:116) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec$$Lambda$3090/1455011356.apply(Unknown Source) ~[?:?]
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_51]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:116) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:157) ~[?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:79) ~[?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel$$Lambda$1983/198024918.accept(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$1985/274580038.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:84) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$0(NetworkHooks.java:74) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks$$Lambda$3081/789133827.apply(Unknown Source) ~[?:?]
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_51]
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:74) ~[?:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147240_a(ClientPlayNetHandler.java:1783) ~[?:?]
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:55) ~[?:?]
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:11) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$3140/942085410.run(Unknown Source) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:861) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?]
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.1.87.jar:28.1]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$383/1768952842.call(Unknown Source) [forge-1.14.4-28.1.87.jar:28.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?]
```

----

What happens in the video:
00:00: Start new world
01:35 Crash server
02:37 Starting a new world from fresh, just mods folder and forge
03:23 GUI doesn't open
03:36 It didn't come to my mind that the exception was client side so I logged out and back in, then restarted the server on a new map, but kept the config folders
04:13 Still can't open GUI
04:25 Log time

**Comment by McJty** [comment]
I'm starting to think it must be a mod interaction. I know it is a lot of work but would it be possible to reproduce this with only rftools and related mods?

**Comment by McJty** [comment]
What mods do you have btw?

**Comment by RakSrinaNa** [comment]
I tried with:
* McjtyLib
* RFToolsBase
* RFToolsUtility
* SilentLib
* Silent's mechanisms

And with:
* McjtyLib
* RFToolsBase
* RFToolsUtility
* RFToolsPower

**Comment by RakSrinaNa** [comment]
For the `NoSuchMethodError` I found it happened in 2 other mods:
* RobertSkalko/Mine-and-Slash/issues/94
* Extegral/Enigmatic-Legacy/issues/6

In both bases the fix seem at add a parameter to the readString method (maybe the length to read?):
* https://github.com/Extegral/Enigmatic-Legacy/commit/76d967374a07dea695a76264fe116ea2cec1c334#diff-d6655c5533d0fd50d991dbd125e2f936
* https://github.com/RobertSkalko/Mine-and-Slash/commit/afd685d7e617b5e4891e6ce66ed0d0a7847c562a#diff-15d145318386b3b4b807de2065edc29c

**Comment by McJty** [comment]
Oh my god. Why is that even marked client only! Ok. easy to fix

**Comment by McJty** [comment]
Just updated new releases of my mods. Hopefully this fixes these issues. Reopen if you still find a problem

**Comment by RakSrinaNa** [comment]
I still saw the discriminator byte message passing by, but the the problem itself seem to be fixed and the crafter crafting 👌
