### ISSUE TITLE
empty syringe in a spawner crashes the game

### ISSUE THREAD

**Issue by Riushda** [McJtyMods/RFToolsUtility#41]
Issue description: Each time I put an empty syringe inside a (charged, i have a flux point on top) spawner the game crashes, it throws an java.lang.NullPointerException. It is possible that the developper forgot the manage the case where there's no essence inside the syringe.

Minecraft version : 1.15.2
forge version : 31.2.30
rftools version : 1.10
McJtyLib version : 4.1.8

```
[20Sep2020 16:28:35.838] [Render thread/FATAL] [net.minecraft.client.Minecraft/]: Reported exception thrown!
net.minecraft.crash.ReportedException: Rendering screen
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:819) ~[?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:924) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553) ~[?:?]
	at net.minecraft.client.main.Main.main(SourceFile:204) ~[minecraft-1.15.2-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_231]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_231]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.15.2-31.2.30-launcher.jar:31.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50) [ForgeWrapper-1.4.2.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_231]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_231]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NullPointerException
	at mcjty.rftoolsutility.modules.spawner.SpawnerConfiguration.getMobData(SpawnerConfiguration.java:784) ~[?:1.15-2.1.10]
	at mcjty.rftoolsutility.modules.spawner.client.GuiSpawner.showSyringeInfo(GuiSpawner.java:98) ~[?:1.15-2.1.10]
	at mcjty.rftoolsutility.modules.spawner.client.GuiSpawner.func_146976_a(GuiSpawner.java:143) ~[?:1.15-2.1.10]
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.render(ContainerScreen.java:73) ~[?:?]
	at mcjty.lib.gui.GenericGuiContainer.render(GenericGuiContainer.java:261) ~[?:1.15-4.1.8]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_231]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_231]
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:745) ~[?:?]
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:798) ~[?:?]
	... 22 more
[20Sep2020 16:28:35.843] [Render thread/INFO] [STDOUT/]: [net.minecraft.util.registry.Bootstrap:func_179870_a:103]: ---- Minecraft Crash Report ----
// Why did you do that?

Time: 9/20/20 4:28 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at mcjty.rftoolsutility.modules.spawner.SpawnerConfiguration.getMobData(SpawnerConfiguration.java:784) ~[?:1.15-2.1.10] {re:classloading}
	at mcjty.rftoolsutility.modules.spawner.client.GuiSpawner.showSyringeInfo(GuiSpawner.java:98) ~[?:1.15-2.1.10] {re:classloading}
	at mcjty.rftoolsutility.modules.spawner.client.GuiSpawner.func_146976_a(GuiSpawner.java:143) ~[?:1.15-2.1.10] {re:classloading}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.render(ContainerScreen.java:73) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at mcjty.lib.gui.GenericGuiContainer.render(GenericGuiContainer.java:261) ~[?:1.15-4.1.8] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368) ~[?:?] {re:classloading}
	at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source) ~[?:?] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_231] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_231] {}
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:745) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:798) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:fairylights:GameRendererTransformer}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:924) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:codechickenlib:IItemRenderer,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:codechickenlib:IItemRenderer,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) ~[minecraft-1.15.2-client.jar:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_231] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_231] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_231] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.15.2-31.2.30-launcher.jar:31.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50) [ForgeWrapper-1.4.2.jar:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_231] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_231] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_231] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}

``` 
EDIT : my bad, it crashes evet if the syringe is not empty.

**Comment by McJty** [comment]
I cannot reproduce this. Can you update to latest version please?

**Comment by Riushda** [comment]
[latest.log](https://github.com/McJtyMods/RFToolsUtility/files/5252383/latest.log)
Here's the latest.log, I have updated McJtyLib to 4.1.9 and rftools utility was already updated to the latest version 2.1.10.

**Comment by Tolana** [comment]
Crashed right-clicking a spawner with a blaze syringe in it.
Minecraft version 1.15.2
Forge Version: 31.2.36
Mcjtylib: 4.1.10
rftoolsbase-1.15-1.1.7
rftoolsutility-1.15-2.1.10
Log: 
[crash-2020-10-05_22.51.59-client.txt](https://github.com/McJtyMods/RFToolsUtility/files/5330087/crash-2020-10-05_22.51.59-client.txt)

**Comment by mcprog** [comment]
This is still an issue. Specifically with the Qtech modpack. Also, your spawner keeps inventory so if you accidentally do this, you have to throw the whole spawner out. Crash report:
`---- Minecraft Crash Report ----
// Shall we play a game?

Time: 10/17/20 3:33 AM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at mcjty.rftoolsutility.modules.spawner.SpawnerConfiguration.getMobData(SpawnerConfiguration.java:784) ~[?:1.15-2.1.10] {re:classloading}
	at mcjty.rftoolsutility.modules.spawner.client.GuiSpawner.showSyringeInfo(GuiSpawner.java:98) ~[?:1.15-2.1.10] {re:classloading}
	at mcjty.rftoolsutility.modules.spawner.client.GuiSpawner.func_146976_a(GuiSpawner.java:143) ~[?:1.15-2.1.10] {re:classloading}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.render(ContainerScreen.java:73) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:findme:generateChest,pl:runtimedistcleaner:A}
	at mcjty.lib.gui.GenericGuiContainer.render(GenericGuiContainer.java:261) ~[?:1.15-4.1.9] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:480) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:924) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) ~[1.15.2.jar:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.15.2-31.2.31.jar:31.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at mcjty.rftoolsutility.modules.spawner.SpawnerConfiguration.getMobData(SpawnerConfiguration.java:784)
	at mcjty.rftoolsutility.modules.spawner.client.GuiSpawner.showSyringeInfo(GuiSpawner.java:98)
	at mcjty.rftoolsutility.modules.spawner.client.GuiSpawner.func_146976_a(GuiSpawner.java:143)
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.render(ContainerScreen.java:73)
	at mcjty.lib.gui.GenericGuiContainer.render(GenericGuiContainer.java:261)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)

-- Screen render details --
Details:
	Screen name: mcjty.rftoolsutility.modules.spawner.client.GuiSpawner
	Mouse location: Scaled: (240, 127). Absolute: (960.000000, 508.000000)
	Screen size: Scaled: (480, 255). Absolute: (1920, 1017). Scale factor of 4.000000

-- Affected level --
Details:
	All players: 4 total; [ClientPlayerEntity['mc1030'/3817, l='MpServer', x=-203.01, y=73.00, z=178.04], RemoteClientPlayerEntity['paigav'/3228, l='MpServer', x=-204.00, y=65.00, z=181.09], RemoteClientPlayerEntity['SolitudeTraveler'/431, l='MpServer', x=-195.44, y=65.00, z=176.12], RemoteClientPlayerEntity['ime990'/3281, l='MpServer', x=-212.09, y=66.00, z=196.96]]
	Chunk stats: Client Chunk Cache: 961, 720
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: -8126824446904606943
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-112,65,209), Chunk: (at 0,4,1 in -7,13; contains blocks -112,0,208 to -97,255,223), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 18276752 game time, 19537222 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:442)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1763)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:567)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_242, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), 
	Memory: 1136245904 bytes (1083 MB) / 3201302528 bytes (3053 MB) up to 5726797824 bytes (5461 MB)
	CPUs: 4
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms6144m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms256m
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.31.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.31.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.31.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.31.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.2.31.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.4.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.4.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.4.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.31
	FML Language Providers: 
		javafml@31.2
		minecraft@1
	Mod List: 
		inventula-1.1.3.jar Inventula {inventula@1.1.3 DONE}
		refinedpipes-0.4.2.jar Refined Pipes {refinedpipes@0.4.2 DONE}
		jei-1.15.2-6.0.3.15.jar Just Enough Items {jei@6.0.3.15 DONE}
		JustEnoughCalculation-1.15.2-3.6.2.jar Just Enough Calculation {jecalculation@3.6.2 DONE}
		lithium-mc1.15.2-forge-0.4.6-rc3-mod.jar Lithium {lithium@0.4.6-rc3 DONE}
		teamsmod-1.15.2-R2-hotfix-2.jar Teams {teamsmod@1.15.2-R2-hotfix DONE}
		Mekanism-1.15.2-9.10.9.422.jar Mekanism {mekanism@9.10.9 DONE}
		SilentMechanisms-1.15.2-0.8.0+59.jar Silent's Mechanisms {silents_mechanisms@0.8.0+59 DONE}
		sleeping_bags-1.15.2-1.0.2.jar Sleeping Bags {sleeping_bags@1.15.2-1.0.2 DONE}
		invtweaks-1.15.2-2.0.9.jar Inventory Tweaks Renewed {invtweaks@1.15.2-2.0.9 DONE}
		findme-1.15.2-1.3.0.jar Find Me {findme@NONE DONE}
		[1.15.2]LagMeter-1.3.1.jar LagMeter {lagmeter@1.3.1 DONE}
		glassential-forge-1.15.2-1.1.4.jar Glassential {glassential@1.1.4 DONE}
		Clumps-5.0.2.6.jar Clumps {clumps@5.0.2.6 DONE}
		XaerosWorldMap_1.11.0_Forge_1.15.2.jar Xaero's World Map {xaeroworldmap@1.11.0 DONE}
		light-overlay-4.7.2.jar Light Overlay Forge {lightoverlay-forge@NONE DONE}
		Controlling-6.1.5.6.jar Controlling {controlling@6.1.5.6 DONE}
		ReAuth-1.14-1.15-3.8.1.jar ReAuth {reauth@3.8.1 DONE}
		Placebo-1.15.2-3.1.0.jar Placebo {placebo@3.1.0 DONE}
		dankstorage-2.6.jar Dank Storage {dankstorage@2.6 DONE}
		NaturesCompass-1.15.2-1.8.5.jar Nature's Compass {naturescompass@1.15.2-1.8.5 DONE}
		Powah-1.15.2-1.1.15.jar Powah {powah@1.1.15 DONE}
		DimStorage-1.15.2-3.1.6.jar DimStorage {dimstorage@3.1.6 DONE}
		theloader-1.15.2-1.1.0.jar The Loader {theloader@1.15.2-1.1.0 DONE}
		Bookshelf-1.15.2-5.6.40.jar Bookshelf {bookshelf@5.6.40 DONE}
		buildinggadgets-3.4.0.jar Building Gadgets {buildinggadgets@3.4.0 DONE}
		mcjtylib-1.15-4.1.9.jar McJtyLib {mcjtylib@1.15-4.1.9 DONE}
		rftoolsbase-1.15-1.1.7.jar RFToolsBase {rftoolsbase@1.15-1.1.7 DONE}
		xnet-1.15-2.1.11.jar XNet {xnet@1.15-2.1.11 DONE}
		DarkUtilities-1.15.2-3.1.8.jar Dark Utilities {darkutils@3.1.8 DONE}
		Morpheus-1.15.2-4.2.50.jar Morpheus {morpheus@version DONE}
		mapperbase-1.15.2-1.1.1.0.jar Mapper Base {mapperbase@1.15.2-1.1.1.0 DONE}
		MekanismGenerators-1.15.2-9.10.9.422.jar Mekanism: Generators {mekanismgenerators@9.10.9 DONE}
		Interactio-1.15.2-3.0.0.jar Interactio {interactio@1.15.2-3.0.0 DONE}
		WaterStrainer-1.15.2-9.0.0.jar Water Strainer {waterstrainer@1.15.2-9.0.0 DONE}
		ToastControl-1.15.2-3.0.1.jar Toast Control {toastcontrol@3.0.1 DONE}
		JEITweaker-1.15.2-1.0.1.3.jar JEI Tweaker {jeitweaker@1.0.1.3 DONE}
		Ma-Essentials-1.15.2-3.1.1.jar Ma Essentials {maessentials@1.15.2-3.1.1 DONE}
		CraftTweaker-1.15.2-6.0.0.44.jar CraftTweaker {crafttweaker@6.0.0.44 DONE}
		rftoolspower-1.15-2.2.5.jar RFToolsPower {rftoolspower@1.15-2.2.5 DONE}
		XNetGases-1.15.2-1.0.0.jar XNet Gases {xnetgases@1.0.0 DONE}
		forge-1.15.2-31.2.31-universal.jar Forge {forge@31.2.31 DONE}
		refinedstorage-1.8.8.jar Refined Storage {refinedstorage@1.8.8 DONE}
		PrettyPipes-1.5.5.jar Pretty Pipes {prettypipes@1.5.5 DONE}
		PackMenu-1.15.2-1.2.4.jar Pack Menu {packmenu@1.2.4 DONE}
		CraftingTweaks_1.15.2-11.0.1.jar Crafting Tweaks {craftingtweaks@11.0.1 DONE}
		forge-1.15.2-31.2.31-client.jar Minecraft {minecraft@1.15.2 DONE}
		industrial-foregoing-1.15.2-2.3.3-e356e61.jar Industrial Foregoing {industrialforegoing@2.3.3 DONE}
		rftoolsutility-1.15-2.1.10.jar RFToolsUtility {rftoolsutility@1.15-2.1.10 DONE}
		TipTheScales-1.15.2-2.0.1.4.jar TipTheScales {tipthescales@2.0.1.4 DONE}
		theoneprobe-1.15-2.0.7.jar The One Probe {theoneprobe@1.15-2.0.7 DONE}
		swingthroughgrass-1.15.2-1.4.0.jar SwingThroughGrass {swingthroughgrass@1.15.2-1.4.0 DONE}
		embellishcraft-1.15.2-2.2.1.0.jar EmbellishCraft {embellishcraft@1.15.2-2.2.1.0 DONE}
		MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		crashutilities-2.10.jar Crash Utilities {crashutilities@2.10 DONE}
		titanium-1.15.2-2.4.2.jar Titanium {titanium@2.4.2 DONE}
		SilentLib-1.15.2-4.6.6+59.jar Silent Lib {silentlib@4.6.6+59 DONE}
		phosphor-forge-mc1.15.2-0.5.2+build.4.jar Phosphor {phosphor@0.5.2+build.4 DONE}
		bluepower-1.15.2-0.4.190-alpha-universal.jar Blue Power {bluepower@0.4.-custom DONE}
		valkyrielib-1.15.2-3.0.2.1.jar ValkyrieLib {valkyrielib@1.15.2-3.0.2.1 DONE}
		simplechunkloaders-1.15.2-1.0.2.0.jar Simple Chunk Loaders {simplechunkloaders@NONE DONE}
		Lollipop-1.15.2-1.0.16.jar Lollipop {lollipop@1.0.16 DONE}
		SilentGear-1.15.2-1.7.5+106.jar Silent Gear {silentgear@1.7.5+106 DONE}
		masonry-1.15.2-0.3.4.jar Masonry {masonry@NONE DONE}
		JACM-1.15.2-2.0.jar Just Another Compass Mod {jacm@2.0 DONE}
		simplybackpacks-1.15.2-1.4.11.jar Simply Backpacks {simplybackpacks@1.15.2-1.4.11 DONE}
		rftoolsbuilder-1.15-2.1.10.jar RFToolsBuilder {rftoolsbuilder@1.15-2.1.10 DONE}
		Xaeros_Minimap_20.23.0_Forge_1.15.2.jar Xaero's Minimap {xaerominimap@20.23.0 DONE}
		JAOPCA-1.15.2-3.2.0.11.jar JAOPCA {jaopca@3.2.0.11 DONE}
		rftoolsstorage-1.15-1.1.10.jar RFToolsStorage {rftoolsstorage@1.15-1.1.10 DONE}
		gravestone-1.17.5.jar Gravestone Mod {gravestone@1.17.5 DONE}
		EnderMagnet-1.15.1-3.0.0.jar Ender Magnet {endermagnet@1.15.1-3.0.0 DONE}
		extlights-2.1.jar Extended Lights {extlights@2.1 DONE}
		config-2-3.0.jar Cloth Config v2 API {cloth-config2@3.0 DONE}
		Harvest-forge-1.15.1-1.2.11-24.jar Harvest {harvest@version DONE}
		elevatorid-1.15.2-1.7.1.jar Elevator Mod {elevatorid@1.15.2-1.7.1 DONE}
		wirelessredstone-1.15.2-0.1.0.jar Wireless Redstone {wirelessredstone@0.1.0 DONE}
		expandedstorage-2.0.0+1.15.2.jar Expanded Storage {expandedstorage@2.0.0 DONE}
		MekanismTools-1.15.2-9.10.9.422.jar Mekanism: Tools {mekanismtools@9.10.9 DONE}
		modular-routers-1.15.2-6.1.3-32.jar Modular Routers {modularrouters@1.15.2-6.1.3-32 DONE}
		trashcans-1.0.3-mc1.15.jar Trash Cans {trashcans@1.0.3 DONE}
		refinedstorageaddons-0.6.3.jar Refined Storage Addons {refinedstorageaddons@0.6.3 DONE}
		extremeSoundMuffler-2.0.1_Forge-1.15.2.jar Extreme Sound Muffler {extremesoundmuffler@2.0.1_forge-1.15.2 DONE}
		SolarGeneration-1.15.2-1.2.2.jar Solar Generation {solargeneration@1.2.2 DONE}
		FastLeafDecay-v22.1.jar FastLeafDecay {fastleafdecay@v22.1 DONE}
		BetterAdvancements-1.15.2-0.1.0.99.jar Better Advancements {betteradvancements@0.1.0.99 DONE}
	Launched Version: 1.15.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Radeon (TM) RX 480 Graphics GL version 4.6.13572 Compatibility Profile Context 19.10.2 26.20.13031.5006, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz`

**Comment by McJty** [comment]
Update RFTools Utility. This is fixed some time ago
