### ISSUE TITLE
RF dialing device can't dial Overworld from other dimensions

### ISSUE THREAD

**Issue by FullMetalMaster** [McJtyMods/RFToolsUtility#59]
idk if theres a way to fix this but it would be great. i can teleport from the end nether or any other dim

**Comment by McJty** [comment]
It can do that. Why wouldn't it be able to do so? Also please more information. What version? Why do you think it doesn't work? What happens?

**Comment by FullMetalMaster** [comment]
RFToolsUtility - 1.16-3.0.19 and the lastest forge and you can dail the end from the over world but nothing shows up in the ends on the dail

**Comment by frank89722** [comment]
I got a similar issue on my 1.16 server
Here's the log when opening a Dialing Device:
```[06.03 18:21:08] [Server] [Server thread/FATAL] [minecraft/ThreadTaskExecutor]: Error executing task on Server
[06.03 18:21:08] [Server] java.lang.NullPointerExceptionnull
[06.03 18:21:08] [Server] 	at mcjty.rftoolsutility.modules.teleporter.blocks.MatterReceiverTileEntity.checkAccess(MatterReceiverTileEntity.java:192) ~[rftoolsutility:1.16-3.0.{re:classloading}
[06.03 18:21:08] [Server] 	at mcjty.rftoolsutility.modules.teleporter.data.TeleportDestinations.getValidDestinations(TeleportDestinations.java:130) ~[rftoolsutility:1.16-3.0.{re:classloading}
[06.03 18:21:08] [Server] 	at mcjty.rftoolsutility.modules.teleporter.blocks.DialingDeviceTileEntity.searchReceivers(DialingDeviceTileEntity.java:167) ~[rftoolsutility:1.16-3.0.{re:classloading}
[06.03 18:21:08] [Server] 	at mcjty.rftoolsutility.modules.teleporter.blocks.DialingDeviceTileEntity.executeWithResultList(DialingDeviceTileEntity.java:274) ~[rftoolsutility:1.16-3.0.{re:classloading}
[06.03 18:21:08] [Server] 	at mcjty.rftoolsutility.modules.teleporter.network.PacketGetReceivers.lambda$handle$0(PacketGetReceivers.java:58) ~[rftoolsutility:1.16-3.0.{re:classloading}
[06.03 18:21:08] [Server] 	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) ~[forge:?] {re:mixin,re:classloading}
[06.03 18:21:08] [Server] 	at mcjty.rftoolsutility.modules.teleporter.network.PacketGetReceivers.handle(PacketGetReceivers.java:49) ~[rftoolsutility:1.16-3.0.{re:classloading}
[06.03 18:21:08] [Server] 	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[forge:?] {re:classloading}
[06.03 18:21:08] [Server] 	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?] {}
[06.03 18:21:08] [Server] 	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) ~[forge:?] {re:classloading}
[06.03 18:21:08] [Server] 	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[forge:?] {re:classloading}
[06.03 18:21:08] [Server] 	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[forge:?] {re:mixin,re:classloading,pl:mixin:APP:performant.mixins.json:forge.SimpleChannelMixin,pl:mixin:A}
[06.03 18:21:08] [Server] 	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
[06.03 18:21:08] [Server] 	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
[06.03 18:21:08] [Server] 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
[06.03 18:21:08] [Server] 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
[06.03 18:21:08] [Server] 	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:84) ~[forge:?] {re:classloading}
[06.03 18:21:08] [Server] 	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:88) ~[forge:?] {re:mixin,re:classloading}
[06.03 18:21:08] [Server] 	at java.util.Optional.map(Optional.java:265) ~[?:?] {}
[06.03 18:21:08] [Server] 	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:88) ~[forge:?] {re:mixin,re:classloading}
[06.03 18:21:08] [Server] 	at net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:1413) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_server_entity_interact,xf:fml:astralsorcery:allow_entity_interaction,pl:mixin:A}
[06.03 18:21:08] [Server] 	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:42) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
[06.03 18:21:08] [Server] 	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:12) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
[06.03 18:21:08] [Server] 	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
[06.03 18:21:08] [Server] 	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
[06.03 18:21:08] [Server] 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
[06.03 18:21:08] [Server] 	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:mixin,re:computing_frames,re:classloading}
[06.03 18:21:08] [Server] 	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:datafixerupper.MinecraftServerMixin,pl:mixin:APP:betterweather.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[06.03 18:21:08] [Server] 	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:datafixerupper.MinecraftServerMixin,pl:mixin:APP:betterweather.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[06.03 18:21:08] [Server] 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
[06.03 18:21:08] [Server] 	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:datafixerupper.MinecraftServerMixin,pl:mixin:APP:betterweather.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[06.03 18:21:08] [Server] 	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:datafixerupper.MinecraftServerMixin,pl:mixin:APP:betterweather.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[06.03 18:21:08] [Server] 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
[06.03 18:21:08] [Server] 	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:696) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:datafixerupper.MinecraftServerMixin,pl:mixin:APP:betterweather.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[06.03 18:21:08] [Server] 	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:datafixerupper.MinecraftServerMixin,pl:mixin:APP:betterweather.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[06.03 18:21:08] [Server] 	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:datafixerupper.MinecraftServerMixin,pl:mixin:APP:betterweather.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[06.03 18:21:08] [Server] 	at java.lang.Thread.run(Thread.java:834) [?:?] {}```

**Comment by McJty** [comment]
Thanks for that crashreport. That was helpful. In the 1.16-3.0.24 release of RFToolsUtility that I just released this should be fixed. Can you all let me know if that helps for the other problems? Those might be related

**Comment by frank89722** [comment]
It's work!
Thank you!
