### ISSUE TITLE
I can't make a world in my modpack

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [McJtyMods/RFToolsUtility#77]
Minecraft Output:

Failed to load datapacks, can't proceed with server load
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Missing required tags: minecraft:item:rftoolsutility:living/highyield,minecraft:item:rftoolsutility:living/living
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1887)
	at net.minecraft.client.Minecraft.func_238189_a_(Minecraft.java:1864)
	at net.minecraft.client.Minecraft.loadWorld(Minecraft.java:1712)
	at net.minecraft.client.Minecraft.func_238192_a_(Minecraft.java:1685)
	at net.minecraft.client.gui.screen.CreateWorldScreen.func_195352_j(CreateWorldScreen.java:260)
	at net.minecraft.client.gui.screen.CreateWorldScreen.lambda$init$11(CreateWorldScreen.java:205)
	at net.minecraft.client.gui.screen.CreateWorldScreen$$Lambda$39070/292930061.onPress(Unknown Source)
	at net.minecraft.client.gui.widget.button.Button.func_230930_b_(SourceFile:33)
	at net.minecraft.client.gui.widget.button.AbstractButton.func_230982_a_(SourceFile:16)
	at net.minecraft.client.gui.widget.Widget.func_231044_a_(Widget.java:136)
	at net.minecraft.client.gui.INestedGuiEventHandler.func_231044_a_(SourceFile:27)
	at net.minecraft.client.MouseHelper.func_198033_b(MouseHelper.java:87)
	at net.minecraft.client.MouseHelper$$Lambda$38440/356562632.run(Unknown Source)
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427)
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85)
	at net.minecraft.client.MouseHelper.func_228030_c_(MouseHelper.java:175)
	at net.minecraft.client.MouseHelper$$Lambda$38163/1743707293.run(Unknown Source)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94)
	at net.minecraft.client.MouseHelper.func_228028_b_(MouseHelper.java:174)
	at net.minecraft.client.MouseHelper$$Lambda$29980/1762306463.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:109)
	at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:305)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:996)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$487/953492906.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
Caused by: java.lang.IllegalStateException: Missing required tags: minecraft:item:rftoolsutility:living/highyield,minecraft:item:rftoolsutility:living/living
	at net.minecraft.tags.NetworkTagManager.lambda$reload$1(NetworkTagManager.java:47)
	at net.minecraft.tags.NetworkTagManager$$Lambda$40427/2019114278.accept(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71)
	at net.minecraft.resources.AsyncReloader$$Lambda$30287/610347199.run(Unknown Source)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127)
	at net.minecraft.client.Minecraft.func_238189_a_(Minecraft.java:1863)
	... 37 more

**Comment by McJty** [comment]
I need more info. All the versions, full log, ...

**Comment by scarha** [comment]
I am getting a similar error, using the latest versions of all the rftools mods and dependencies.

**Comment by McJty** [comment]
'latest version' is not a real version. Always post exact numbers because when I look back at this report in the future the value of 'latest' has changed.

Also I still need logs

**Comment by scarha** [comment]
rftoolsbase-1.16-2.0.10
rftoolsbuilder-1.16-3.0.16
rftoolscontrol-1.16-4.0.8
rftoolsdim-1.16-7.0.7-beta
rftoolspower-1.16-3.0.8
rftoolsstorage-1.16-2.0.11
rftoolsutility-1.16-3.0.25
mcjtylib-1.16-5.0.19

I've also emailed you the log.
