### ISSUE TITLE
RFToolsUtility has failed to load correctly

### ISSUE THREAD

**Issue by huhridge** [McJtyMods/RFToolsUtility#91]
Using curseforge to load a modpack using this mod on the M1 MacBook Air, the mod refuses to load. 
The java version is 1.8.0_74 and forge version is 34.1.42.
The error log is enclosed:

Mod File: rftoolsutility-1.16-3.0.22.jar
	Failure message: RFToolsUtility (rftoolsutility) has failed to load correctly
		java.lang.ArrayIndexOutOfBoundsException: 64
	Mod Version: 1.16-3.0.22
	Mod Issue URL: http://github.com/McJtyMods/RFToolsUtility/issues
	Exception message: java.lang.ArrayIndexOutOfBoundsException: 64
Stacktrace:
	at it.unimi.dsi.fastutil.objects.Object2IntOpenCustomHashMap.rehash(Object2IntOpenCustomHashMap.java:1154) ~[fastutil-8.2.1.jar:?] {re:classloading}
	at it.unimi.dsi.fastutil.objects.Object2IntOpenCustomHashMap.insert(Object2IntOpenCustomHashMap.java:305) ~[fastutil-8.2.1.jar:?] {re:classloading}
	at it.unimi.dsi.fastutil.objects.Object2IntOpenCustomHashMap.put(Object2IntOpenCustomHashMap.java:313) ~[fastutil-8.2.1.jar:?] {re:classloading}
	at net.minecraft.util.registry.SimpleRegistry.func_243537_a(SourceFile:81) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.util.registry.SimpleRegistry.func_218382_a(SourceFile:72) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.util.registry.SimpleRegistry.func_218381_a(SourceFile:103) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.util.registry.Registry.func_218322_a(Registry.java:456) ~[?:?] {re:classloading,re:mixin}
	at mcjty.rftoolsutility.modules.spawner.recipes.SpawnerRecipeType.register(SpawnerRecipeType.java:11) ~[?:1.16-3.0.22] {re:classloading}
	at mcjty.rftoolsutility.modules.spawner.SpawnerModule.<init>(SpawnerModule.java:49) ~[?:1.16-3.0.22] {re:classloading}
	at mcjty.rftoolsutility.RFToolsUtility.setupModules(RFToolsUtility.java:68) ~[?:1.16-3.0.22] {re:classloading}
	at mcjty.rftoolsutility.RFToolsUtility.<init>(RFToolsUtility.java:40) ~[?:1.16-3.0.22] {re:classloading}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_74] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_74] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_74] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_74] {}
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_74] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[?:34.1] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:110) ~[?:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) ~[?:1.8.0_74] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618) ~[?:1.8.0_74] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_74] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_74] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_74] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_74] {}

**Comment by McJty** [comment]
What version of mcjtylib and rftoolsbase do you have?

**Comment by huhridge** [comment]
mcjtylib - mcjtylib-1.16-5.0.16.jar
rftoolsbase - rftoolsbase-1.16-2.0.10.jar

**Comment by McJty** [comment]
Those are all very old versions. I recommend updating.
